export const UPLOAD_STARTED = 'UPLOAD_STARTED'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_ERROR = 'UPLOAD_ERROR'
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS'

export const REQUEST_FINISHED_UPLOADS = 'REQUEST_FINISHED_UPLOADS'
export const RECEIVE_FINISHED_UPLOADS = 'RECEIVE_FINISHED_UPLOADS'
export const FINISHED_UPLOADS_ERROR = 'FINISHED_UPLOADS_ERROR'

export const DRAGOVER_STARTED = 'DRAGOVER_STARTED'
export const DRAGOVER_ENDED = 'DRAGOVER_ENDED'

export const REQUEST_DELETE_UPLOAD = 'REQUEST_DELETE_UPLOAD'
export const UPLOAD_DELETED = 'UPLOAD_DELETED'
export const DELETE_UPLOAD_ERROR = 'DELETE_UPLOAD_ERROR'

export const ABORT_UPLOAD = 'ABORT_UPLOAD'
export const UPLOAD_ABORTED = 'UPLOAD_ABORTED'

export const CHANGE_UPLOAD_STATUS = 'CHANGE_UPLOAD_STATUS'
export const REMOVE_UPLOAD = 'REMOVE_UPLOAD'
