export const UPLOAD_STARTED = 'UPLOAD_STARTED'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_ERROR = 'UPLOAD_ERROR'
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS'

export const REQUEST_FINISHED_UPLOADS = 'REQUEST_FINISHED_UPLOADS'
export const RECEIVE_FINISHED_UPLOADS = 'RECEIVE_FINISHED_UPLOADS'
export const FINISHED_UPLOADS_ERROR = 'FINISHED_UPLOADS_ERROR'

export const DRAGOVER_STARTED = 'DRAGOVER_STARTED'
export const DRAGOVER_ENDED = 'DRAGOVER_ENDED'
