# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import web.core


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.CharField(blank=True, default=web.core.random_slug_default_length, max_length=64),
        ),
    ]
