# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import web.core


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_file_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(blank=True, max_length=4096, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.CharField(default=web.core.random_slug_default_length, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('key', 'author')]),
        ),
    ]
